#  ansible < n1 /n2/ g1/ g2 > -m file -a "path=~/02_new_dir state=directory"
---

# FIRST PLAY --> multiple tasks
- name: Deply Web App
  hosts: n2
  remote_user: centos
  become: yes

  tasks:
  - name: Install git
    yum:
      name: git
      state: present

  - name: Start HTTPD
    service:
      name: httpd
      state: started

  - name: Enable HTTPD
    service:
      name: httpd
      state: started

  - name: Host the code
    git:
      repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
      dest: /var/www/html
...