#  ansible < n1 /n2/ g1/ g2 > -m file -a "path=~/02_new_dir state=directory"
---

# FIRST PLAY --> multiple tasks
- name: Install HTTPD server
  hosts: n2
  remote_user: centos
  become: yes

  tasks:
  - name: Install HTTPD
    yum:
      name: httpd
      state: present

  - name: Start HTTPD
    service:
      name: httpd
      state: started

  - name: Enable HTTPD
    service:
      name: httpd
      state: started
...